# Site settings
title: Oliver Sherouse
email: oliver.sherouse@gmail.com
description: > # this means to ignore newlines until "baseurl:"
  Oliver Sherouse writes on Data, Python, and Culture
baseurl: "" # the subpath of your site, e.g. /blog/

url: "http://www.oliversherouse.com" # the base hostname & protocol for your site

gems: [jekyll-paginate, jekyll-coffeescript]
paginate: 10
paginate_path: "/blog/page:num/"

defaults:
  -
    scope:
      path: "" # an empty string here means all files in the project
      type: "posts" # previously `post` in Jekyll 2.2.
    values:
      layout: "post"

kramdown:
  input: GFM
  hard_wrap: false

highlighter: rouge
gist:
  noscript: false
