# Site settings
title: Oliver Sherouse
email: oliver.sherouse@gmail.com
description: > # this means to ignore newlines until "baseurl:"
  Oliver Sherouse writes on Data, Python, and Culture
baseurl: "" # the subpath of your site, e.g. /blog/

url: "http://www.oliversherouse.com" # the base hostname & protocol for your site
highlighter: rouge
paginate: 10
paginate_path: "/blog/page:num/"
